services:
  api:
    build: .
    container_name: api
    # Command to run the app with hot-reloading for development
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mount the current directory into the container for live code changes.
      # This also ensures the SQLite database file is persisted on the host.
      - .:/app
    ports:
      - "8000:8000"
    